# Navbar Menus

[[nav]]
    name    = "About"
    url     = "/#about"
    weight  = 2
[[nav]]
    name    = "Events"
    url     = "/#events"
    weight  = 3
[[nav]]
    name    = "Rules"
    url     = "/#coc"
    weight  = 4
[[nav_right]]
    name    = "Log in"
    url     = "https://members.theotowngarage.com"
    weight  = 5
    [[nav_right.params]]
        icon    = "user"
# The last item is highlighted
[[nav_right]]
    name    = "Become a member"
    url     = "/#memberships"
    weight  = 6